# Http Server
server:
  port: 8888
# Spring
spring:
  cloud:
    config:
      enabled: false
      name: config-server
      server:
        git:
          refreshRate: 5
          skip-ssl-validation: true
          uri: https://github.com/dmgicarloi/server-config
          username: carlo368723@hotmail.com
          password: dmgicarloi2020