# Spring
spring:
  application:
    name: reports
  config:
    import: optional:configserver:http://localhost:8888/
# Http
server:
  port: 8000
  servlet:
    context-path: /api
# Eureka Client
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: -*